@startuml

'アクター
actor 社員

'バウンダリ
boundary ノルマ免除申請画面アクセス #skyblue
boundary エラー画面 #red 
boundary ノルマ免除申請画面表示 #skyblue

'コントロール
control 申請者情報取得
note left of 申請者情報取得
申請者者情報はサービスで保持していないため、
BFFで取得してリクエストとして渡す
endnote
control 権限チェック
control 管理職ノルマ免除申請取得
control 管理職ノルマ免除申請初期生成

'エンティティ
entity 申請者 #pink
entity 管理職ノルマ免除申請 #pink

'処理概要
社員 --> ノルマ免除申請画面アクセス
ノルマ免除申請画面アクセス --> 申請者情報取得
申請者情報取得 - 申請者
申請者情報取得 --> 権限チェック
権限チェック -> エラー画面 : 管理職ではない場合
権限チェック --> 管理職ノルマ免除申請取得 : 管理職の場合
管理職ノルマ免除申請取得 -> 管理職ノルマ免除申請
管理職ノルマ免除申請取得 --> 管理職ノルマ免除申請初期生成 :　取得できない場合
管理職ノルマ免除申請取得 --> ノルマ免除申請画面表示
管理職ノルマ免除申請初期生成 --> ノルマ免除申請画面表示

@enduml
