@startuml

'アクター
actor 人財部

'バウンダリ
boundary ノルマ免除申請 #skyblue
boundary エラー画面 #red 
boundary ノルマ免除申請画面表示 #skyblue

'コントロール
control 認可者情報取得
note left of 認可者情報取得
申請者者情報はサービスで保持していないため、
BFFで取得してリクエストとして渡す
endnote
control 権限チェック
control 管理職ノルマ免除申請取得
control 管理職ノルマ免除申請初期生成
control 差戻
note left of 差戻
・ステータス「差戻」は「申請中」からのみなりうるため
　それ以外のステータスはエラーとする
・差し戻し理由は必須
endnote

'エンティティ
entity 認可者 #pink
entity 管理職ノルマ免除申請 #pink

'処理概要
人財部 --> ノルマ免除申請
ノルマ免除申請 --> 認可者情報取得
認可者情報取得 - 認可者
認可者情報取得 --> 権限チェック
権限チェック -> エラー画面 : 人財部ではない場合
権限チェック --> 管理職ノルマ免除申請取得 : 人財部の場合
管理職ノルマ免除申請取得 -> 管理職ノルマ免除申請
管理職ノルマ免除申請取得 --> 管理職ノルマ免除申請初期生成 :　取得できない場合
管理職ノルマ免除申請取得 --> 差戻
管理職ノルマ免除申請初期生成 --> 差戻
差戻 --> ノルマ免除申請画面表示

@enduml
