@startuml
top to bottom direction

hide circle
hide method

package 360度評価 {

    package 360度評価集約{
        
        object 360度評価リスト {
            + ノルマ計算()
        }
        object 360度評価 {
            ID
            評価期間ID
            査定値ID
            良い点
            改善点
            提出状況
        }
        object 提出者 {
            skyID
        }   
        object 対象者 {
            skyID
        }          
        object 役職 {
            役職ID
            役職レベル
            管理職フラグ
        }   
        360度評価リスト *-down- 360度評価
        360度評価 *-right- 提出者
        360度評価 *-right- 対象者
        提出者 *-down- 役職
        対象者 *-down- 役職
        note bottom of 360度評価
        ・提出状況は「保存」「提出」「提出後保存」
        end note
        note right of 360度評価リスト
        ノルマ仕様
        ・管理職(課長代理以上)
        評定経路外の上中下問わず管理職に3人
        ・リーダ〜係長
        評定経路外の上中下に3人
        ・一般以下
        評定経路外の上中に2人
        ※EGG、EGGアシスタントは一般と同等レベルとみなす
        ※ノルマは360度評価終了日時点の評定経路者、役職の関係から算出する
        end note
    }


    package 評定経路集約{
        object 評定経路リスト {
            評価期間ID
            対象者SkyID
        }
        object 評定経路 {
            評価者SkyID
            ステージ
        }
    } 
    評定経路リスト *-down- 評定経路 : 1..n
    360度評価リスト -left-> 評定経路リスト

    package 評価期間集約{
        object 評価期間リスト {
        }

        object 評価期間 {
            ID
            360度評価開始日
            360度評価終了日
        }
    }
    評価期間リスト *-down- 評価期間 : 1..n
    360度評価 -left-> 評価期間 

    package 査定値集約 {
        object 査定値リスト {
        }

        object 査定値 {
            ID
            査定値
        }
    }
    査定値リスト *-down- 査定値 : 1..n

    package ノルマ申請集約{
        object ノルマ申請 {
            ID
            評価期間ID
        }
        object 申請者 {
            skyID
        }   
        object 申請者役職 {
            役職ID
            役職レベル
            管理職フラグ
        }   
        object ノルマ詳細 {
        }
        object ノルマ詳細管理職 {
            ID
            ノルマ申請ID
            免除人数        
        }
        object ノルマ詳細管理職以外 {
            ID
            ノルマ申請ID
            関係 
        }
        object 申請状況{
        }
        object 申請状況差戻{
            ステータス
            申請理由
            差戻理由
        }
        object 申請状況未提出{
            ステータス
        }
        object 申請状況申請中承認{
            ステータス
            申請理由
        }
        ノルマ申請 *-down- ノルマ詳細 : 1 .. n
        ノルマ詳細 <|-down- ノルマ詳細管理職
        ノルマ詳細 <|-down- ノルマ詳細管理職以外
        ノルマ申請 *-left- 申請者 : 1 1
        ノルマ申請 *-down- 申請状況 : 1 1
        申請者 *-down- 申請者役職
        申請状況 <|-down- 申請状況未提出
        申請状況 <|-down- 申請状況申請中承認
        申請状況 <|-down- 申請状況差戻
    }
}
@enduml
