@startuml
top to bottom direction

hide circle
hide method

package 休職休業システム {

    package クエリモデル{

        object 申請 {
            申請id
            skyid
            休業種別
            休業状態
            休業開始日
            休業終了日
        }
    }

    package 産休申請集約{

        object 産休申請{
            申請id
            skyid
            休業状態
        }

        object 産休開始申請{
            出産予定日
            多胎かどうか
            休業開始日
            休業終了予定日
            仮申請かどうか
            母子手帳
            承認
        }

        object 産休休業前手続き {
            動画確認
        }

        object 産休休業中申請{
            出産日
            承認状態
        }

        object 産休復帰{
            復帰日
        }

        産休申請 *-down- 産休開始申請
        産休申請 *-down- 産休休業前手続き
        産休申請 *-down- 産休休業中申請
        産休申請 *-down- 産休復帰

        note bottom of 産休開始申請
        ・出産予定日以前42日間(多胎98日間)、出産後56日間
        ・出産予定日を超えて出産した場合、出産日から56日間
        ・6週間を経過した後は医師の判断で就業可能
        end note

        note bottom of 産休復帰
        ・産後は6週間は強制的な休業
        ・6週間を経過した後は医師の判断で就業可能
        end note
    }

    package 育休申請集約{

        object 育休申請{
            申請id,
            skyid,
        }

        object 育休開始申請{
            産休予定日
            認可
        }

        object 育休休業前手続き {
            動画確認
        }

        object 育休休業中申請{
            出産日
            承認
        }

        object 育休復帰{
            復帰日
        }

        育休申請 *-down- 育休開始申請
        育休申請 *-down- 育休休業前手続き
        育休申請 *-down- 育休休業中申請
        育休申請 *-down- 育休復帰
    }

    package 出生時育児休業申請集約{

        object 出生時育児休業申請{
            id
            skyid
            出産予定日
            休業開始日
            休業終了予定日
            休業開始日2
            休業終了予定日2
            仮申請か
        }

        object 申請認可{
            上長skyid
            上長認可状態
            総務認可状態
        }

        object 期間変更申請{
            出生日
            休業開始日
            休業終了予定日
            休業開始日2
            休業終了予定日2
        }

        object 期間変更申請認可{
            申請種別（通常申請、期間変更）
            上長skyid
            上長認可状態
            総務認可状態
        }

        object 休業前手続き {
            給付金控除を受ける
            扶養かどうか
            送信状況
            動画確認
        }

        object 休業中報告{
            出産日
            名前
            族柄
        }

        object 復業{
            復帰日
        }

        object 復業申請認可{
            上長skyid
            上長認可状態
            総務認可状態
        }

        出生時育児休業申請 *-down- 申請認可
        出生時育児休業申請 *-down- 休業前手続き
        出生時育児休業申請 *-down- 期間変更申請
        期間変更申請 *-down- 期間変更申請認可
        出生時育児休業申請 *-down- 休業中報告
        出生時育児休業申請 *-down- 復業
        復業 *-down- 復業申請認可
    }

    ' package 出生時育児休業申請集約{

    '     object 出生時育児休業申請{
    '         申請id
    '         skyid
    '         休業状態
    '         休業
    '     }

    '     object 出生時育児休業開始申請{
    '         出産予定日
    '         休業開始日
    '         休業終了予定日
    '         承認
    '     }

    '     object 出生時育児休業前手続き {
    '         動画確認
    '     }

    '     object 出生時育児休業中申請{
    '         出産日
    '         承認状態
    '     }

    '     object 出生時育児休業復帰{
    '         復帰日
    '     }

    '     出生時育児休業申請 *-down- 出生時育児休業開始申請
    '     出生時育児休業申請 *-down- 出生時育児休業前手続き
    '     出生時育児休業申請 *-down- 出生時育児休業中申請
    '     出生時育児休業申請 *-down- 出生時育児休業復帰
    ' }

    package 男性育休申請集約{

        object 男性育休申請{
            申請id,
            skyid,
        }

        object 男性育休開始申請{
            産休予定日
            認可
        }

        object 男性育休休業前手続き {
            動画確認
        }

        object 男性育休休業中申請{
            出産日
            承認
        }

        object 男性育休復帰{
            復帰日
        }

        男性育休申請 *-down- 男性育休開始申請
        男性育休申請 *-down- 男性育休休業前手続き
        男性育休申請 *-down- 男性育休休業中申請
        男性育休申請 *-down- 男性育休復帰
    }
}
@enduml
