@startuml
top to bottom direction

hide circle
hide method

package 昇格推薦レポート {

    package レポート設定集約 {
        object レポート設定{
            ID
            レポート設定有無
            テーマ
            文字数
        }

        object レポート設定リスト{
            ID
            評価期間ID
            設定者skyID
            設定日
        }

        object 役職層 {

        }

        レポート設定リスト *-down- レポート設定 : 1 .. n
        レポート設定 *-down- 役職層
        note left of レポート設定
        ・テーマ自体の制限なし
        ・文字数の制限なし
        　※社長層は対象外
        end note
        note left of 役職層
        ・セクション層=降格役職
        ・それ以外=役職レベル単位
        　※社長層は対象外
        end note
    }
}
@enduml
