@startuml

'アクター
actor 人財部

'バウンダリ
boundary アクセス権限画面アクセス #skyblue
boundary エラー画面 #red 
boundary アクセス権限画面 #skyblue

'コントロール
control 権限チェック #Yellow
control アクセス権限取得
control 部署リスト取得 #Yellow
control アクセス権限と部署をマージ #Yellow
control アクセス権限と部署をマージ #Yellow

'エンティティ
entity アクセス権限 #pink

'処理概要
人財部 --> アクセス権限画面アクセス
アクセス権限画面アクセス --> 権限チェック
権限チェック -> エラー画面 : 人財部以外の場合
権限チェック --> アクセス権限取得 :人財部の場合
アクセス権限取得 - アクセス権限
アクセス権限取得 --> 部署リスト取得 :アクセス権限が空の場合
部署リスト取得 --> アクセス権限と部署をマージ
アクセス権限と部署をマージ --> アクセス権限画面
アクセス権限取得 --> アクセス権限画面

@enduml
