@startuml

top to bottom direction

'アクター
actor 昇格候補書

'バウンダリ
boundary レポート保存 #skyblue
boundary レポート画面表示 #skyblue
boundary エラー画面 #red

'コントロール
control 権限チェック #Yellow
control レポート取得
control 初期レポート生成
control レポートを保存する
note left of レポートを保存する
・提出済みの場合はエラー
・承諾、辞退どちらも未回答の場合はエラー
・承諾の場合はレポート内容が必須
　※レポート文字数は問わない
・辞退の場合は辞退理由が必須
・ドメインの状態を変えるとともにイベントを返却する
end note 
control レポート保存イベントをDBに保存する
control レポートプロジェクトをDBに保存する

'エンティティ
entity レポート #pink

'処理概要
昇格候補書 --> レポート保存
レポート保存 --> 権限チェック
権限チェック --> レポート取得
権限チェック -> エラー画面 : 対象期の昇格候補者以外が保存した場合
レポート取得 - レポート
レポート取得 --> 初期レポート生成 : 一度も保存していない場合
レポート取得 --> レポートを保存する
初期レポート生成 - レポート
初期レポート生成 --> レポートを保存する
レポートを保存する - レポート
レポートを保存する  --> レポート保存イベントをDBに保存する
レポート保存イベントをDBに保存する --> レポートプロジェクトをDBに保存する
レポートプロジェクトをDBに保存する --> レポート画面表示

@enduml