@startuml

top to bottom direction

'アクター
actor 人財部

'バウンダリ
boundary レポート設定画面アクセス #skyblue
boundary レポート設定画面表示 #skyblue
boundary エラー画面 #red

'コントロール
control 権限チェック #Yellow
control レポート設定リスト取得
control 初期レポートリスト設定生成
note right of 初期レポートリスト設定生成
役職層から生成する
end note 

'エンティティ
entity レポート設定リスト #pink

'処理概要
人財部 --> レポート設定画面アクセス
レポート設定画面アクセス --> 権限チェック
権限チェック --> レポート設定リスト取得
権限チェック -> エラー画面 : 人財部以外がアクセスした場合
レポート設定リスト取得 - レポート設定リスト
レポート設定リスト取得 --> レポート設定画面表示
レポート設定リスト取得 --> 初期レポートリスト設定生成 : 一度も保存していない場合
初期レポートリスト設定生成 --> レポート設定画面表示


@enduml