@startuml

left to right direction

'アクター
actor 人財部
actor 社長


'バウンダリ
boundary レポート設定画面アクセス 
boundary レポート設定画面表示
boundary アクセス権限エラー画面 #red

'コントロール
control 権限チェック
control レポート設定取得
note left of レポート設定取得
既に保存されたレポート設定ある場合はそのデータから画面表示する
※1回も保存されていない場合は初期データからレポート設定を生成する
end note
control 初期レポート設定生成

'エンティティ
entity レポート設定 #pink

'処理概要
人財部 -> レポート設定画面アクセス
社長 -> レポート設定画面アクセス
レポート設定画面アクセス -> 権限チェック
権限チェック -> レポート設定取得
権限チェック --> アクセス権限エラー画面 : 社長、人財部以外がアクセスした場合
レポート設定取得 --> レポート設定
レポート設定取得 -> レポート設定画面表示
レポート設定取得 -> 初期レポート設定生成
初期レポート設定生成 -> レポート設定画面表示



@enduml