@startuml

top to bottom direction

'アクター
actor 人財部

'バウンダリ
boundary レポート設定保存ボタン押下 #skyblue
boundary レポート設定画面表示 #skyblue
boundary エラー画面 #red

'コントロール
control 権限チェック #Yellow
control レポート設定リスト取得
control 初期レポートリスト設定生成
note left of 初期レポートリスト設定生成
役職層から生成する
end note 
control レポート設定リスト保存
note left of レポート設定リスト保存 
・入力有かつ、テーマがない/文字数がない場合はエラー
・締切日後は変更できない
end note 
control レポート設定リストDB削除
control レポート設定リストDB保存
control レポート設定リスト再取得

'エンティティ
entity レポート設定リスト #pink

'処理概要
人財部 --> レポート設定保存ボタン押下
レポート設定保存ボタン押下 --> 権限チェック
権限チェック --> レポート設定リスト取得
レポート設定リスト取得 -right- レポート設定リスト
権限チェック -> エラー画面 : 人財部以外が保存した場合
レポート設定リスト取得 --> 初期レポートリスト設定生成 : 取得できない場合
初期レポートリスト設定生成 -right- レポート設定リスト
レポート設定リスト取得 -> レポート設定リスト保存
初期レポートリスト設定生成 --> レポート設定リスト保存
レポート設定リスト保存 - レポート設定リスト
レポート設定リスト保存 --> レポート設定リストDB削除
レポート設定リストDB削除 --> レポート設定リストDB保存
レポート設定リストDB保存 --> レポート設定リスト再取得 
レポート設定リスト再取得 --> レポート設定画面表示

@enduml