@startuml

top to bottom direction

'アクター
actor 社長
actor 岡田さん
actor アクセス権限者

'バウンダリ
boundary 昇格推薦一覧画面 #skyblue
boundary 昇格推薦一覧検索結果画面 #skyblue
boundary エラー画面 #red

'コントロール
control 権限チェック #Yellow
control 昇格候補者一覧取得 #Yellow
note left of 昇格候補者一覧取得
・アクセス権限による絞り込みはされている前提
end note 
control レポートリスト取得
control レポート提出状況による絞り込み
note left of レポート提出状況による絞り込み
・未回答/承諾/辞退、
　未認可/認可済み/却下で対象者を絞り込む
・対象者のSkyIdリストを返す
end note 
control メール送信状況による絞り込み
note left of メール送信状況による絞り込み
・メール送信機能完了後に実装する
end note 
control 部署による絞り込み
note bottom of 部署による絞り込み
・対象部署に属する
　SkyIdリストを取得する
・サービスが既にある想定
end note 
control 役職による絞り込み
note bottom of 役職による絞り込み
・対象役職の
　SkyIdリストを取得する
・サービスが既にある想定
end note 
control 社員ID氏名による絞り込み
note bottom of 社員ID氏名による絞り込み
・対象社員ID,氏名の
　SkyIdリストを取得する
.サービスない場合、新規作成
end note 
control 対象者を取得した情報を基に絞り込み #Yellow


'処理概要
社長 --> 昇格推薦一覧画面
岡田さん --> 昇格推薦一覧画面
アクセス権限者 --> 昇格推薦一覧画面
昇格推薦一覧画面 --> 権限チェック
権限チェック --> 昇格候補者一覧取得
権限チェック -> エラー画面 : 社長、岡田さん、アクセス権限者以外の場合
昇格候補者一覧取得 --> レポートリスト取得 : 昇格推薦サービス
昇格候補者一覧取得 --> 部署による絞り込み : 社員検索サービス
昇格候補者一覧取得 --> 役職による絞り込み : 社員検索サービス
昇格候補者一覧取得 --> 社員ID氏名による絞り込み : 社員検索サービス
レポートリスト取得 --> レポート提出状況による絞り込み
レポート提出状況による絞り込み --> メール送信状況による絞り込み
メール送信状況による絞り込み --> 対象者を取得した情報を基に絞り込み
部署による絞り込み --> 対象者を取得した情報を基に絞り込み
役職による絞り込み --> 対象者を取得した情報を基に絞り込み
社員ID氏名による絞り込み ----> 対象者を取得した情報を基に絞り込み
対象者を取得した情報を基に絞り込み --> 昇格推薦一覧検索結果画面

@enduml